name: Scala CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'adopt'
    - name: compile
      run: sbt compile
    - name: Run sbt clean coverage test
      run: sbt clean coverage test
    - name: aggregate coverage
      run: sbt coverageAggregate
    - name: Check for cobertura.xml in coverage report directory
      run: ls -l /home/runner/work/Carcassonne/Carcassonne/target/scala-3.3.4/coverage-report
    - name: Run sbt coverageReport
      run: sbt coverageReport
    - name: Submit coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: sbt coveralls
